spring.application.name=secureapp

# SSL Config
server.ssl.key-store=/home/ec2-user/keystore.p12
server.ssl.key-store-password=${SSL_PASSWORD:123456}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
server.ssl.enabled=true

# Trust Store para mutual TLS
server.ssl.trust-store=/home/ec2-user/truststore.p12
server.ssl.trust-store-password=${SSL_PASSWORD:123456}
server.ssl.trust-store-type=PKCS12
server.ssl.client-auth=WANT